Add custom cursor
SYMBIO/next-devstack pull request #82
Opened 2020-11-05 16:31 UTC by tessik

2020-11-05 17:02 UTC, vonschau reviewed
Nemuzu si pomoct, ale prijde mi to hrozne na miru sity symbio webu a tak nevim, jestli to patri do devstacku

2020-11-05 18:38 UTC, mrondra commented on src/components/primitives/CustomCursor/CustomCursor.tsx
> +        <div ref={cursorRef} className={styles.wrapper} style={{ left: 0, top: 0 }}>
tady by asi ten style nemusel být?

2020-11-05 18:41 UTC, mrondra commented
pořád nevím, jestli by to řešení bez refs nebylo lepší, když slouží jen k nastavení stylů

2020-11-09 11:17 UTC, vonschau commented
Cus,

hele asi k tomu budu potrebovat aspon nejaky strucny popis, jak si teda takovy custom cursor udelam. Dejme tomu, ze mam napr. nejakej div, nad kterym chci cusom cursor - jak to s timhle resenim udelam?

V.

2020-11-09 13:08 UTC, tessik commented
> Cus,
> 
> hele asi k tomu budu potrebovat aspon nejaky strucny popis, jak si teda takovy custom cursor udelam. Dejme tomu, ze mam napr. nejakej div, nad kterym chci cusom cursor - jak to s timhle resenim udelam?
> 
> V.

Cus, jde o ten "zakladni" kurzor, ke kteremu vlastne neni zadani. Je to custom globalni kurzor, jde jen o vzhled, nic neumi. V symbiowebu bych na nem stavel a pridal funkcionalitu pro ruzne situace a neprijde mi vhodne to resit v obecne komponente.

Jeste k tomu, jestli to patri do devstacku - nevim, mne prislo ze ano. :) Klidne to pak smazu, ale chci si to primergovat do sve vetve v devstacku.

2020-11-09 13:11 UTC, vonschau commented
A je to nekde videt? Otevrel jsem si ten deployment, ale kurzor mam normalni.

2020-11-10 13:19 UTC, mrondra commented
Za mě by bylo lepší kdyby složka cursors/ byla dál ještě rozsložkovaná ať v tom je pořádek. A je tam na mě moc "any" toho by se asi chtělo zbavit. Jinak HOC je good, ale lepší by asi bylo mít to jako klasickou komponentu a přes children. Takhle s tím bude víc práce, když budu chtít např. v cyklu mít na každý komponentě cursor a ne globálně na wrapperu.

2020-11-10 14:05 UTC, vonschau commented
Vidim posun k lepsimu.

Slozku cursors chapu jako slozku, kam se davaj ty vlastni kurzory - to je pro me docela citelne. To, co resi logiku (aktualne HOC) a render (aktualne picovina :)) je pak ve standardnich slozkach. Proti tomu asi nic nemam.

Ta komponenta CustomCursor je od posledne asi netknuta, tak tu zatim nehodnotim.
Taky bych asi radsi klasik komponentu a ne HOC, pokud to bude mozne.

2020-11-12 11:29 UTC, mrondra commented
já bych řekl, že good :)

2020-11-12 11:32 UTC, mrondra approved these changes

2020-11-12 12:52 UTC, vonschau requested changes

2020-11-12 12:52 UTC, vonschau commented on src/components/primitives/CustomCursor/CustomCursor.module.scss
> +}
@jantesarek tenhle soubor ma jit pryc

2020-11-12 16:05 UTC, vonschau approved these changes

2020-11-12 16:15 UTC, merged